### PR TITLE
Hotfix/memory issues

### LINKED ISSUE #250: Crash when entering invalid characters into memory
When entering invalid characters like `-` into the memory, the simulator crashes.
Example: When entering `-` at address 0 in 8bit bin mode, the following assertion error happens:
```
Assertion failed: (begin < end) at line 236 in file memory-value.cpp
terminate called after throwing an instance of 'assert::AssertionError'
  what():  Assertion failed: (begin < end) at line 236 in file memory-value.cpp
```
backtrace:
```
Thread 5 "era-sim" received signal SIGABRT, Aborted.


Thread 6 (Thread 0x7fffcd679700 (LWP 7459)):
#0  0x00007ffff75df10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007ffff53372ac in __gthread_cond_wait (__mutex=<optimized out>, 
    __cond=__cond@entry=0x2e23a28)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:864
#2  std::condition_variable::wait (this=this@entry=0x2e23a28, __lock=...)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00000000005563c3 in std::condition_variable::wait<Scheduler::_run()::<lambda()> > (
    __p=..., __lock=..., this=0x2e23a28) at /usr/include/c++/6.2.1/condition_variable:99
#4  Scheduler::_run (this=0x2e239b0)
    at /home/jan/Documents/era-gp-Urlaub/era-gp-sim/source/core/scheduler.cpp:55
#5  0x00007ffff533d31f in std::execute_native_thread_routine (__p=0x2dbb170)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#6  0x00007ffff75d9454 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff4ab17df in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffcde7a700 (LWP 7458)):
#0  0x00007ffff49fc04f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff49fd47a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff53134bd in __gnu_cxx::__verbose_terminate_handler ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff5311276 in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff53112c1 in std::terminate ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff533d34e in std::execute_native_thread_routine (__p=0xed2ca0)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:91
#6  0x00007ffff75d9454 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff4ab17df in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffd7fff700 (LWP 7457)):
#0  0x00007ffff4aa848d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff281a786 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff281a89c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#3  0x00007ffff58e62bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff588fd3a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#5  0x00007ffff56b2063 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#6  0x00007ffff6a4ce75 in ?? () from /usr/lib/libQt5Qml.so.5
#7  0x00007ffff56b6cf8 in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff75d9454 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff4ab17df in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffdcb2a700 (LWP 7456)):
#0  0x00007ffff4aa848d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff281a786 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff281a89c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff58e62bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff588fd3a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#5  0x00007ffff56b2063 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#6  0x00007fffea33ade5 in ?? () from /usr/lib/libQt5DBus.so.5
#7  0x00007ffff56b6cf8 in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff75d9454 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff4ab17df in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffe9cc9700 (LWP 7455)):
#0  0x00007ffff4aa848d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff06f98e0 in ?? () from /usr/lib/libxcb.so.1
#2  0x00007ffff06fb679 in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x00007fffec4f9789 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff56b6cf8 in ?? () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff75d9454 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff4ab17df in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7f2f800 (LWP 7451)):
#0  0x00007ffff4aa848d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff281a786 in ?? () from /usr/lib/libglib-2.0.so.0
```

### PR DESCRIPTION
**Pull request by janschopohl**
closes #250 

Also some further improvements/fixes to memory and register components.

### CODE REVIEW

File: source/ui/memory-component-presenter.cpp [hunk 1]
```diff
@@ -50,18 +47,18 @@ void MemoryComponentPresenter::onMemoryChanged(std::size_t address,
 
   // if the memory that is hold in cache is changed, invalidate cache
   // new value intersects with the beginning of the cached region
-  bool overlap_beginning =
+  bool overlapBeginning =
```
Comment (goldsborough) [inline source/ui/memory-component-presenter.cpp]: Couldn't we reduce this to `(address >= begin && address <= end) || ((address + length) >= begin && (address + length) <= end)`. We just care about an overlap anywhere

File: source/ui/memory-component-presenter.cpp [hunk 2]
```diff
@@ -195,23 +164,23 @@ MemoryComponentPresenter::dataInfo(const QModelIndex &index, int role) const {
 
 
 MemoryValue MemoryComponentPresenter::getMemoryValueCached(
-    const std::size_t memory_address, const std::size_t memory_length) const {
+    const std::size_t memoryAddress, const std::size_t memoryLength) const {
```
Comment (goldsborough) [inline source/ui/memory-component-presenter.cpp]: This function is quite long. Consider splitting it up.

File: source/ui/memory-component-presenter.cpp [hunk 3]
```diff
@@ -195,23 +164,23 @@ MemoryComponentPresenter::dataInfo(const QModelIndex &index, int role) const {
...
   // check for cache
-  if (_memoryCacheValid && memory_address >= _memoryCacheBaseAddress &&
-      memory_address + memory_length <=
+  if (_memoryCacheValid && memoryAddress >= _memoryCacheBaseAddress &&
+      memoryAddress + memoryLength <=
```
Comment (goldsborough) [inline source/ui/memory-component-presenter.cpp:166]: Thanks for renaming the variables. Looks like noone reviewed these changes when they first came in :disappointed:

File: source/ui/memory-component-presenter.cpp [hunk 4]
```diff
@@ -237,38 +206,46 @@ MemoryValue MemoryComponentPresenter::getMemoryValueCached(
...
+    {ValueRoleDecS32, "SignedDecimalData32"},
+    {ValueRoleDecS64, "SignedDecimalData64"},
+    {InfoRole, "info"}
+  };
+  // clang-format on
   return roles;
 }
+
+QString MemoryComponentPresenter::_roleToDataFormat(const QString &role) {
+  QString dataFormat = role;
```
Comment (goldsborough) [inline source/ui/memory-component-presenter.cpp]: `auto`

File: source/ui/memory-component-presenter.cpp [hunk 5]
```diff
@@ -237,38 +206,46 @@ MemoryValue MemoryComponentPresenter::getMemoryValueCached(
...
+  if (dataFormat.endsWith("8")) {
```
Comment (goldsborough) [inline source/ui/memory-component-presenter.cpp]: What happens for `BinaryData128`? Better use a regular expression. `QString` has [nice support for this](http://doc.qt.io/qt-5/qstring.html#remove-4):

```
// Take by value
QString MemoryComponentPresenter::_roleToDataFormat(QString role) {
  return role.remove(QRegularExpression("\\d+$"));
}
```
something like that

**Review by goldsborough — APPROVED** [review]
Looks good. Just a few comments. We can merge this after [`feature/theme-memory`](#261) has landed
